import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../idms.html',import.meta.url),'utf8');
const img=fs.readFileSync(new URL('./fixtures/engineering-drawing-gost-validation.jpg',import.meta.url));
assert.ok(img.length>10000,'validation drawing fixture exists');
assert.match(html,/function rfqStrictEvidenceSanitize\(chars\)/,'strict evidence gate exists');
assert.match(html,/derived\/inferred characteristic/,'derived dimensions are rejected');
assert.match(html,/concentricity has no visible concentricity symbol/,'datum-only concentricity is rejected');
assert.match(html,/function rfqDrawingReadyForExport\(r\)/,'hard export readiness gate exists');
assert.match(html,/VERIFIED DRAWING/,'verified state is visible on printed drawing');
assert.match(html,/NOT VERIFIED — DO NOT USE FOR INSPECTION/,'unsafe export is visibly blocked');
assert.match(html,/Adversarial final coverage audit/,'final coverage audit exists');
assert.ok(html.includes('±0.05 means upper +0.05 and lower -0.05'),'plus-minus rule remains enforced');
console.log('engineeringdrawingv132test: PASS');
