// Controlled MCP gateway for Ruflo. Read-only manufacturing context plus one draft-only write.
import { sql, ensureTables, cors } from '../_db.js';
const tools=[['ironvale_get_rfq','Read one RFQ by reference',['ref']],['ironvale_get_drawing','Read drawing-related RFQ/part data',['ref','partId']],['ironvale_get_part','Read one manufacturing part',['partId','partNo']],['ironvale_get_bom','Read BOM records',['partId']],['ironvale_get_process','Read process/routing records',['partId']],['ironvale_get_machine_capability','Read enabled CNC machine capability',['machineId']],['ironvale_get_material_options','Read material records',['partId']],['ironvale_get_quality_requirements','Read PFMEA/control-plan/PPAP/inspection records',['partId']],['ironvale_get_previous_quotes','Read previous RFQ/quotation context',['customer','partNo']],['ironvale_get_costing_data','Read costing records',['partId']],['ironvale_save_ai_proposal','Save a reviewable AI proposal; never release/send it',['ref','proposal']]].map(([name,description,required])=>({name,description,inputSchema:{type:'object',properties:Object.fromEntries(required.map(k=>[k,{type:k==='proposal'?'object':'string'}])),required:name==='ironvale_save_ai_proposal'?required:[]}}));
const clean=(v,n=300)=>String(v??'').slice(0,n);
const auth=req=>{const k=String(process.env.IRONVALE_MCP_KEY||'').trim();const x=String(req.headers['x-mcp-key']||'').trim();const a=String(req.headers.authorization||'').trim();const bearer=a.toLowerCase().startsWith('bearer ')?a.slice(7).trim():'';return !!k&&(x===k||bearer===k);};
const ok=(id,result)=>({jsonrpc:'2.0',id,result});const err=(id,code,message)=>({jsonrpc:'2.0',id,error:{code,message}});
async function rfq(ref){const r=await sql`SELECT data FROM rfqs WHERE ref=${String(ref).trim().toUpperCase()}`;return r[0]?.data||null;}
async function docs(kind,partId=''){return partId?await sql`SELECT doc_id,kind,part_id,doc_no,rev,status,data,updated_at,updated_by FROM idms_docs WHERE kind=${kind} AND part_id=${partId} ORDER BY updated_at DESC LIMIT 100`:await sql`SELECT doc_id,kind,part_id,doc_no,rev,status,data,updated_at,updated_by FROM idms_docs WHERE kind=${kind} ORDER BY updated_at DESC LIMIT 100`;}
async function part(a){if(a.partId){const r=await sql`SELECT * FROM idms_parts WHERE part_id=${clean(a.partId)} LIMIT 1`;return r[0]||null;}if(a.partNo){const r=await sql`SELECT * FROM idms_parts WHERE part_no=${clean(a.partNo)} ORDER BY updated_at DESC LIMIT 1`;return r[0]||null;}return null;}
async function call(name,a={}){
if(name==='ironvale_get_rfq')return{rfq:await rfq(a.ref)};
if(name==='ironvale_get_drawing'){const r=a.ref?await rfq(a.ref):null,p=a.partId?await part(a):null;return{ref:a.ref||null,partId:a.partId||null,drawing:r?.drawing||r?.drawingData||r?.file||r?.attachment||p?.data?.drawing||null,fileName:r?.fileName||r?.drawingFileName||null};}
if(name==='ironvale_get_part')return{part:await part(a)};if(name==='ironvale_get_bom')return{records:await docs('bom',a.partId||'')};if(name==='ironvale_get_process')return{records:await docs('process',a.partId||'')};
if(name==='ironvale_get_machine_capability'){const r=a.machineId?await sql`SELECT doc_id AS machine_id, doc_no AS name, data->>'controller' AS controller, data->>'adapter' AS adapter, true AS enabled, status AS state, updated_at FROM idms_docs WHERE kind='machine' AND status <> 'Disabled' AND doc_id=${clean(a.machineId)} LIMIT 1`:await sql`SELECT doc_id AS machine_id, doc_no AS name, data->>'controller' AS controller, data->>'adapter' AS adapter, true AS enabled, status AS state, updated_at FROM idms_docs WHERE kind='machine' AND status <> 'Disabled' ORDER BY doc_id LIMIT 100`;return{records:r};}
if(name==='ironvale_get_material_options')return{records:await docs('material',a.partId||'')};
if(name==='ironvale_get_quality_requirements'){const o={};for(const k of ['pfmea','control_plan','ppap','dimension','msa','process'])o[k]=await docs(k,a.partId||'');return o;}
if(name==='ironvale_get_previous_quotes'){const c=clean(a.customer),p=clean(a.partNo);const r=c?await sql`SELECT data FROM rfqs WHERE upper(data->>'customer')=upper(${c}) ORDER BY created_at DESC LIMIT 50`:p?await sql`SELECT data FROM rfqs WHERE upper(coalesce(data->>'partNo',data->>'part_no',''))=upper(${p}) ORDER BY created_at DESC LIMIT 50`:await sql`SELECT data FROM rfqs ORDER BY created_at DESC LIMIT 50`;return{records:r.map(x=>x.data)};}
if(name==='ironvale_get_costing_data')return{records:await docs('costing',a.partId||'')};
if(name==='ironvale_save_ai_proposal'){const ref=String(a.ref||'').trim().toUpperCase(),existing=await rfq(ref);if(!existing)throw new Error('RFQ not found.');const proposal=a.proposal&&typeof a.proposal==='object'?a.proposal:{};const saved={...existing,aiProposal:{...proposal,savedAt:new Date().toISOString(),status:'Draft - Human Review Required',source:'Ruflo'}};await sql`UPDATE rfqs SET data=${JSON.stringify(saved)}::jsonb WHERE ref=${ref}`;return{saved:true,ref,status:saved.aiProposal.status,releaseAllowed:false};}
throw new Error('Unknown tool: '+name);}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(200).end();if(req.method==='GET')return res.status(200).json({ok:true,service:'IRONVALE MCP',authentication:'X-MCP-Key or Authorization: Bearer required for JSON-RPC POST'});if(!auth(req))return res.status(401).json(err(null,-32001,'Unauthorized MCP client'));try{await ensureTables();if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});const b=typeof req.body==='string'?JSON.parse(req.body):(req.body||{}),id=b.id??null;if(b.method==='initialize')return res.status(200).json(ok(id,{protocolVersion:'2024-11-05',capabilities:{tools:{listChanged:false},resources:{listChanged:false},prompts:{listChanged:false}},serverInfo:{name:'IRONVALE Manufacturing MCP',version:'1.0.0'},instructions:'Controlled manufacturing data gateway for Ruflo.'}));if(b.method==='notifications/initialized')return res.status(202).end();if(b.method==='ping')return res.status(200).json(ok(id,{pong:true}));if(b.method==='tools/list')return res.status(200).json(ok(id,{tools}));if(b.method==='tools/call'){const name=b.params?.name;if(!tools.some(t=>t.name===name))return res.status(200).json(err(id,-32601,'Tool not found: '+name));return res.status(200).json(ok(id,{content:[{type:'text',text:JSON.stringify(await call(name,b.params?.arguments||{}))}],isError:false}));}return res.status(200).json(err(id,-32601,'Method not found: '+b.method));}catch(e){return res.status(200).json(err(null,-32603,e.message));}}
